coincollector_project/coincollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
]

coincollector_project/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('coins/', views.coins_index, name='index'),
    path('coins/<int:coin_id>/', views.coins_detail, name='detail'),
    path('coins/create/', views.CoinCreate.as_view(), name='coins_create'),
    path('coins/<int:pk>/update/', views.CoinUpdate.as_view(), name='coins_update'),
    path('coins/<int:pk>/delete/', views.CoinDelete.as_view(), name='coins_delete'),
    path('coins/<int:pk>/add_purchase/', views.add_purchase, name='add_purchase'),
    
    path('coins/<int:pk>/assoc_investor/<int:investor_pk>/', views.assoc_investor, name='assoc_investor'),
    path('coins/<int:pk>/assoc_delete/<int:investor_pk>', views.assoc_delete, name='assoc_delete'),

    path('investors/', views.InvestorList.as_view(), name='investors_index'),
    path('investors/<int:pk>/', views.InvestorDetail.as_view(), name='investors_detail'),
    path('investors/create/', views.InvestorCreate.as_view(), name='investors_create'),
    path('investors/<int:pk>/update/', views.InvestorUpdate.as_view(), name='investors_update'),
    path('investors/<int:pk>/delete/', views.InvestorDelete.as_view(), name='investors_delete'),

]

coincollector_project/main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Investor(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('coins_detail', kwargs={'pk': self.id})
        
class Coin(models.Model):
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=50)
    price = models.FloatField()
    description = models.TextField(max_length=250)
    investors = models.ManyToManyField(Investor)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'coin_id': self.id})

class Purchase(models.Model):
    date = models.DateField()
    dollar_amount = models.FloatField()
    coin_amount = models.FloatField()

    # coin_id FK
    coin = models.ForeignKey(Coin, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.coin_amount} on {self.date}'
    
    class Meta:
        ordering = ['-date']

coincollector_project/main_app/forms.py
from django.forms import ModelForm
from .models import Purchase

class PurchaseForm(ModelForm):
  class Meta:
    model = Purchase
    fields = ['date', 'coin_amount', 'dollar_amount']

coincollector_project/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from .models import Coin, Investor
from .forms import PurchaseForm

"""
coins = [
    {'name': 'Bitcoin', 'symbol': 'BTC', 'price': '63,332.98'},
    {'name': 'Ethereum', 'symbol': 'ETH', 'price': '3,247,03'},
    {'name': 'Dogecoin', 'symbol': 'DOGE', 'price': '0.1475'},
]
"""

# Create your views here.
def home(request):
    return render(request, 'coins/home.html')

def about(request):
    return render(request, 'coins/about.html')

def coins_index(request):
    coins = Coin.objects.all()
    return render(request, 'coins/index.html', {
        'coins': coins
    })

def coins_detail(request, coin_id):
    coin = Coin.objects.get(id=coin_id)
    investors = Investor
    id_list = coin.investors.all().values_list('id')
    investors_not = Investor.objects.exclude(id__in=id_list)
    purchase_form = PurchaseForm()
    return render(request, 'coins/detail.html', {
        'coin': coin,
        'purchase_form': purchase_form,
        'investors': investors_not,
    })

def add_purchase(request, pk):
    form = PurchaseForm(request.POST)

    if form.is_valid():
        new_purchase = form.save(commit=False)
        new_purchase.coin_id = pk
        new_purchase.save()
    return redirect('detail', coin_id=pk)

def assoc_investor(request, pk, investor_pk):
  Coin.objects.get(id=pk).investors.add(investor_pk)
  return redirect('detail', coin_id=pk)

def assoc_delete(request, pk, investor_pk):
    Coin.objects.get(id=pk).investors.remove(investor_pk)
    return redirect('detail', coin_id=pk)

class CoinCreate(CreateView):
  model = Coin
  fields = ['name', 'symbol', 'price', 'description']

class CoinUpdate(UpdateView):
  model = Coin
  fields = ['price', 'description']

class CoinDelete(DeleteView):
  model = Coin
  success_url = '/coins'

class InvestorList(ListView):
  model = Investor

class InvestorDetail(DetailView):
  model = Investor

class InvestorCreate(CreateView):
  model = Investor
  fields = ['name']

class InvestorUpdate(UpdateView):
  model = Investor
  fields = ['name']

class InvestorDelete(DeleteView):
  model = Investor
  success_url = '/investors'

coincollector_project/main_app/templates/coins/about.html
{% extends 'coins/base.html' %}
{% block content %}
    <h1 class="text-4xl mb-10 ml-8 mt-5">About the Coin Collector</h1>
    <p>The coin collector was ... </p>
{% endblock %}

coincollector_project/main_app/templates/coins/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Coin Collector</title>
  <!--
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  -->
  {% tailwind_css %}

</head>
<body class="bg-blue-700 bg-square-pattern min-h-screen flex flex-col font-serif">
  <header>
    <nav class="bg-blue-300 opacity-70">
      <div class="container mx-auto flex items-center justify-between">
        <ul>
          <li class="text-5xl mt-5 mb-8"><a href="{% url 'home' %}">Coin Collector</a></li>
        </ul>
        <ul class="flex items-end justify-around">
          <li class="mr-10"><a href="{% url 'about' %}">About</a></li>
          <li class="mr-10"><a href="{% url 'coins_create' %}">Add a Coin</a></li>
          <li class="mr-10"><a href="{% url 'index' %}">View All Coins</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="flex-1">
    {% block content %}
    {% endblock %}
  </main>
  <footer>
    All Rights Reserved, &copy; {% now "Y" %} Coin Collector
  </footer>
</body>
</html>

coincollector_project/main_app/templates/coins/detail.html
{% extends 'coins/base.html' %}
{% block content %}
<div>
    <div>
        <span><h3 class="text-2xl font-semibold">{{ coin.name }}</h3></span>
        <p>{{ coin.symbol }}</p>
        <p>${{ coin.price }}</p></p>
        <p>{{ coin.description }}</p>
    </div>
    <div class="mt-5">
        <a href="{% url 'coins_update' coin.id %}" class="text-lg font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-2 px-4 border border-black hover:border-transparent rounded">Edit</a>
        <a href="{% url 'coins_delete' coin.id %}" class="text-lg font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-2 px-4 border border-black hover:border-transparent rounded">Delete</a>
    </div>
    <div>
        <form action="{% url 'add_purchase' coin.id %}"  method="POST" class="mt-10">
            {% csrf_token %}
            <!-- Render the inputs -->
            <table>{{ purchase_form.as_table }}</table>
            <input type="submit" class="text-lg font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-2 px-4 border border-black hover:border-transparent rounded mt-5" value="Add Purchase">
        </form>
        
        <table class="mt-10">
          <thead>
            <tr><th>Date</th><th>Dollar Amount</th><th>Coin Amount</th></tr>
          </thead>
          <tbody>
            {% for purchase in coin.purchase_set.all %}
                    <tr>
                        <td>{{purchase.date}}</td>
                        <td>{{purchase.coin_amount}}</td>
                        <td>{{purchase.dollar_amount}}</td>
                    </tr>
            {% endfor %}
          </tbody>
        </table>
      </div> 
      <div>
        <h3 class="text-xl mt-5 font-semibold">{{ coin.name }}'s Investors</h3>
        {% if coin.investors.count %}
          {% for investor in coin.investors.all %}
            <div>
                <span>
                    {{ investor.name }}
                </span>
            </div>
            <div>
                <form action="{% url 'assoc_delete' coin.id investor.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="text-md font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-1 px-2 border border-black hover:border-transparent rounded mt-5">Remove</button>
                </form>
            </div>
          {% endfor %}
        {% else %}
          <h5>No Investors</h5>
        {% endif %}
    </div>
    <h3 class="text-xl mt-5 font-semibold">Available Investors</h3>
  {% if investors.count %}
    {% for investor in investors.all %}
        <div>
          <span>
            {{ investor.name }}
          </span>
        </div>
        <div>
          <form action="{% url 'assoc_investor' coin.id investor.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="text-md font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-1 px-2 border border-black hover:border-transparent rounded">Add</button>
          </form>
        </div>
    {% endfor %}
  {% else %}
    <h5>{{coin.name}} Has All Investors Available</h5>
  {% endif %}
</div>



{% endblock %}

coincollector_project/main_app/templates/coins/home.html
{% extends 'coins/base.html' %}
{% block content %}
    <h1 class="text-4xl mb-10 ml-8 mt-5"><em>Home Page</em></h1>
{% endblock %}

coincollector_project/main_app/templates/coins/index.html
{% extends 'coins/base.html' %}
{% block content %}
    <h1 class="text-4xl mb-8 ml-8 mt-5">Coins List</h1>
    
    {% for coin in coins %}
        <div>
            <a href="{% url 'detail' coin.id %}">
                <div class="mb-8 ml-10 py-2 px-4 bg-white opacity-80 rounded border border-blue-800">
                    <span class="text-2xl">{{ coin.name }}</span>
                    <p>{{ coin.symbol }}</p>
                    <p>${{ coin.price }}</p></p>
                    <p>{{ coin.description }}</p>
                </div>
            </a>
        </div>
    {% endfor %}

{% endblock %}

coincollector_project/main_app/templates/main_app/coin_confirm_delete.html
{% extends 'coins/base.html' %}

{% block content %}
<h1>Delete Coin</h1>

<h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>

<form action="" method="POST">
{% csrf_token %}
<input type="submit" value="Yes - Delete!">
<a href="{% url 'detail' coin.id %}">Cancel</a>
</form>
{% endblock %}

coincollector_project/main_app/templates/main_app/coin_form.html
{% extends 'coins/base.html' %}

{% block content %}
  {% if object %}
    <h1 class="text-4xl mb-10 ml-8 mt-5">Edit <span>{{object.name}}</span></h1>
  {% else %}
    <h1 class="text-4xl mb-10 ml-8 mt-5">Add Coin</h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <table class="ml-12 mb-10">
      {{ form.as_table }}
    </table>
    <input class="ml-72 text-lg font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-2 px-4 border border-black hover:border-transparent rounded" type="submit" value="Submit!">
  </form>
{% endblock %}

coincollector_project/main_app/templates/main_app/investor_confirm_delete.html
{% extends 'coins/base.html' %}

{% block content %}
  <h1>Delete Investor</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'investors_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

coincollector_project/main_app/templates/main_app/investor_detail.html
{% extends 'coins/base.html' %}

{% block content %}

<h1>Investor Details</h1>
<div >
    <div>
        <span>{{ investor.name }}</span>
    </div>
    <div>
        <a href="{% url 'investors_update' investor.id %}">Edit</a>
        <a href="{% url 'investors_delete' investor.id %}">Delete</a>
    </div>
</div>
{% endblock %}

coincollector_project/main_app/templates/main_app/investor_form.html
{% extends 'coins/base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span>{{object.name}}</span></h1>
  {% else %}
    <h1 class="text-2xl mb-5">Add Investor</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="text-lg font-semibold bg-blue-600 hover:bg-blue-800 text-black hover:text-white py-2 px-4 border border-black hover:border-transparent rounded mt-5">
  </form>
{% endblock %}

coincollector_project/main_app/templates/main_app/investor_list.html
{% extends 'coins/base.html' %}
{% block content %}

<h1>Investor List</h1>

{% for investor in investor_list %}
  <a href="{% url 'investors_detail' investor.id %}">
    <div>
        <span>{{ investor.name }}</span>
    </div>
  </a>
{% endfor %}

{% endblock %}

coincollector_project/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>